<a href="https://colab.research.google.com/github/natyrix/tensorflow/blob/main/tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf


In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

In [6]:
string = tf.Variable("STRING VARIABLE", tf.string)
number = tf.Variable(232, tf.int16)
floating = tf.Variable(2.22, tf.float64)

# Rank/Degree of Tensors

In [7]:
rank1 = tf.Variable(["TEST"], tf.string)
rank2 = tf.Variable([["RANK2", "TEST"], ["TESTING", "YES"]], tf.string)

## Determine rank

In [8]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of tensors

In [9]:
rank2.shape

TensorShape([2, 2])

## Changing Shape

In [25]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [22]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
